//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDS325__Indice_Académico_Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asignatura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Asignatura()
        {
            this.Seccion = new HashSet<Seccion>();
        }
    
        public string CodigoAsignatura { get; set; }
        public string CodigoCarrera { get; set; }
        public string CodigoArea { get; set; }
        public int Credito { get; set; }
        public string NombreAsignatura { get; set; }
        public Nullable<System.DateTime> FechaIngresoAsignatura { get; set; }
        public Nullable<bool> VigenciaAsignatura { get; set; }
    
        public virtual AreaAcademica AreaAcademica { get; set; }
        public virtual Carrera Carrera { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seccion> Seccion { get; set; }
    }
}
