//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDS325__Indice_Académico_Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calificacion
    {
        public int Matricula { get; set; }
        public string CodigoAsignatura { get; set; }
        public string Trimestre { get; set; }
        public string Nota { get; set; }
        public Nullable<int> IdSeccion { get; set; }
        public Nullable<System.DateTime> FechaIngresoCalificacion { get; set; }
        public Nullable<bool> VigenciaCalificacion { get; set; }
    
        public virtual Seccion Seccion { get; set; }
        public virtual Persona Persona { get; set; }
    }
}
