//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDS325__Indice_Académico_Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Literal
    {
        public string Nota { get; set; }
        public Nullable<decimal> Numero { get; set; }
    }
}
