//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDS325__Indice_Académico_Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seccion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Seccion()
        {
            this.Calificacion = new HashSet<Calificacion>();
        }
    
        public string CodigoAsignatura { get; set; }
        public int IdSeccion { get; set; }
        public Nullable<int> Matricula { get; set; }
        public Nullable<System.DateTime> FechaIngresoSeccion { get; set; }
        public Nullable<bool> VigenciaSección { get; set; }
        public Nullable<int> NumeroSección { get; set; }
    
        public virtual Asignatura Asignatura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Calificacion> Calificacion { get; set; }
        public virtual Persona Persona { get; set; }
    }
}
